twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_4_layout.html.twig']
    globals:
       categories_p: '@App\Repository\CategoryRepository'
       cart_c: '@App\Service\Cart\Cart'
when@test:
    twig:
        strict_variables: true
